#landing pre connexion
innolcl_front_homepage:
    path:     /
    defaults: { _controller: innoLCLfrontBundle:Default:index }

#landing phase 1
innolcl_front_landing_proposal:
    path:     /proposal
    defaults: { _controller: innoLCLfrontBundle:Default:proposal }

#landing phase 2
innolcl_front_landing_selection:
    path:     /selection
    defaults: { _controller: innoLCLfrontBundle:Default:selection }

#landing phase 3
innolcl_front_landing_laureat:
    path:     /laureats
    defaults: { _controller: innoLCLfrontBundle:Default:laureat }

#landing phase 4
innolcl_front_landing_vote:
    path:     /votes
    defaults: { _controller: innoLCLfrontBundle:Default:vote }

#landing test date de la phase 4
innolcl_front_landing_vote_testeur:
    path:     /votes/{Y}/{M}/{d}/{h}/{m}/{s}
    defaults: { _controller: innoLCLfrontBundle:Default:votetesteur }
    requirements:
        Y:  \d+
        M:  \d+
        d:  \d+
        h:  \d+
        m:  \d+
        s:  \d+

#landing phase 5
innolcl_front_landing_results:
    path:     /results
    defaults: { _controller: innoLCLfrontBundle:Default:results }


#soumission js set video as seen
innolcl_frontbundle_videohandleFormAction:
    path:     /videoseen
    defaults: { _controller: innoLCLfrontBundle:Video:handleForm }
    methods:  [POST]

#requete js get newideaform /!\ Pas sur que cet route soit utilisé
innolcl_front_landing_getnewideaform:
    path:     /getnewideaform
    defaults: { _controller: innoLCLfrontBundle:Default:getnewideaform }
    methods:  [POST]

#incremente le compteur Video
innolcl_front_videoincrement:
    path:    /videoincrement/{name}
    defaults: { _controller: innoLCLfrontBundle:Video:incrementStatCounter }



#landing pre connexion
front_online_version:
    path:     /online/{type}/{hash}
    defaults: { _controller: innoLCLfrontBundle:Online:index }


#mentions-legales
innolcl_front_page_mentions:
    path:     /mentions-legales
    defaults: { _controller: innoLCLfrontBundle:Pages:mentions }

#reglement
innolcl_front_page_reglement:
    path:     /reglement
    defaults: { _controller: innoLCLfrontBundle:Pages:reglement }

#modedemploi
innolcl_front_page_manual:
    path:     /modedemploi
    defaults: { _controller: innoLCLfrontBundle:Pages:manual }
