<?php

namespace innoLCL\bothIdeaBundle\Entity;

/**
 * IdeaLaureatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IdeaLaureatRepository extends \Doctrine\ORM\EntityRepository
{
}
