<?php

namespace innoLCL\bothIdeaBundle\Entity;

/**
 * ReviewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReviewRepository extends \Doctrine\ORM\EntityRepository
{
	/**
    * Donne les reviews passés effectués par un user (moderateur)
    */
    public function getPreviousList(Idea $idea, $user) {
		$query = $this->createQueryBuilder('r')
                ->where('r.moderateur = :moderateur')
                ->setParameter('moderateur', $user)
                ->andWhere('r.idea = :idea')
                ->setParameter('idea', $idea)
                ->andWhere('r.versionIdea < :ideaversion')
                ->setParameter('ideaversion', $idea->getVersion())
                ->orderBy('r.versionIdea','asc');
                
		return $query->getQuery()->getResult();
	}
	
	/**
    * Donne la review actuelle effectué par un user (moderateur) 
    */
    public function getCurrent(Idea $idea, $user) {
		$query = $this->createQueryBuilder('r')
                ->where('r.moderateur = :moderateur')
                ->setParameter('moderateur', $user)
                ->andWhere('r.idea = :idea')
                ->setParameter('idea', $idea)
                ->andWhere('r.versionIdea = :ideaversion')
                ->setParameter('ideaversion', $idea->getVersion());
                
		return $query->getQuery()->getOneOrNullResult();
	}
}
