<?php

namespace innoLCL\StatBundle\Entity;

/**
 * VideoStatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VideoStatRepository extends \Doctrine\ORM\EntityRepository
{
}
