<?php

namespace innoLCL\StatBundle\Entity;

/**
 * VotesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VotesRepository extends \Doctrine\ORM\EntityRepository
{
  public function findLastVoteByUser($id) {
    $qb = $this->createQueryBuilder('v')
               ->Where('v.user = :user')
               ->setParameter('user', $id)
               ->add('orderBy','v.dateVote DESC')
               ->setMaxResults(1);

    return $qb->getQuery()->getOneOrNullResult();
  }
  public function getTotalVoteCount() {
    $qb = $this->createQueryBuilder('v')
               ->select('count(v.id)');
    return $qb->getQuery()->getSingleScalarResult();
  }
}
